#提示语部分  支持 &颜色字符 与 §颜色字符  1.8保存请用ASNI编码 1.9+请用UTF-8编码
#############################################
#gjing:当玩家在挂机时但是却输入了/gj on所提示的信息
#nogj:当玩家不在挂机时但是却输入了/gj off所提示的信息
#gjrun:挂机开始提示信息
#gjdone:挂机结束提示信息
#usecmd:当玩家挂机时输入了其他指令
#############################################
gjing: "&6&l[挂机插件] &e&l-> &a你正在挂机..."
nogj: "&6&l[挂机插件] &e&l-> &a你不在挂机..."
gjrun: "&6&l[挂机插件] &e&l-> &a挂机中..."
gjdone: "&6&l[挂机插件] &e&l-> &a挂机结束"
usecmd: "&6&l[挂机插件] &e&l-> &a你无法在挂机状态下使用其他指令"

#领地区域挂机
Residence:
  #开启区域挂机
  Enable: false
  #区域名(领地名)
  Name: "test"
  #不在任何一块领地时
  NoInAResidence: "&6&l[挂机插件] &e&l-> &c你不在任何一块领地中"
  #不在正确的领地时
  NoInRightResidence: "&6&l[挂机插件] &e&l-> &7你不在一块能挂机的领地中,你需要站在领地 &e%res_name% &7才能使用"
  
#相关选项
#############################################
#周期(period):修改这个就能够更改每多少秒进行一次经验的给予或者是金币的给予 单位:秒
period: 2
#金币:每循环一个周期则给的金币，修改为0则不给予 需要小数
money: 0.05
#经验:每循环一个周期则给的经验，不是经验等级而是经验！  我记得好像wiki上有每个等级所需的经验值的相关信息
exp: 2

#全息设置
#############################################
# id:设置悬浮物品的id
# data:设置悬浮物品的特殊值如 35:6 后面的6就是特殊值
# Line:设置悬浮字
Item: 
  id: 2261
  data: 0
Line: "&c&l[挂机中]"